export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_PLAYLISTS:"SET_PLAYLISTS",
    SET_USER:"SET_USER",
    SET_PLAYLIST:"SET_PLAYLIST",
    SET_PLAYING:"SET_PLAYING",
    SET_PLAYER_STATE:"SET_PLAYER_STATE",
    SET_FOOTER_VISIBILITY: 'SET_FOOTER_VISIBILITY',
    SET_SEARCH_FOOTER: 'SET_SEARCH_FOOTER',
    SET_AUDIO: "SET_AUDIO",
    SET_CURRENT_TRACK_INDEX: 'SET_CURRENT_TRACK_INDEX',
    SET_TRACKS :'SET_TRACKS',
    SET_CURRENT_TRACK_INDEX : 'SET_CURRENT_TRACK_INDEX',
    
    SET_PLAYLIST_ID:"SET_PLAYLIST_ID",
    SONG_PLAYING:"SONG_PLAYING",
    // Add other reducer cases if needed
  };
  